# Generated by Django 3.2.7 on 2021-09-24 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 24, 18, 21, 48, 77943, tzinfo=utc), null=True),
        ),
    ]
