# Generated by Django 3.2.7 on 2021-09-25 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0002_alter_reservation_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='car_price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hoursDriving',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='kms',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 25, 14, 55, 32, 328435, tzinfo=utc), null=True),
        ),
    ]
