# Generated by Django 3.2.7 on 2021-09-25 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0003_auto_20210925_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 25, 15, 7, 49, 602556, tzinfo=utc), null=True),
        ),
    ]
