# Generated by Django 3.2.7 on 2021-09-27 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0026_auto_20210927_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 27, 22, 22, 3, 168363, tzinfo=utc), null=True),
        ),
    ]
