# Generated by Django 3.2.7 on 2021-09-27 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0027_alter_reservation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 27, 22, 48, 20, 743905, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
