# Generated by Django 3.2.7 on 2021-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0029_alter_reservation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='location_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='selected_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='selected_kms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
