# Generated by Django 3.2.7 on 2021-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0030_auto_20210928_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='selected_hours',
            new_name='selected_hours_kms_price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='location_price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='selected_kms',
        ),
    ]
