# Generated by Django 3.2.7 on 2021-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0031_auto_20210928_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='selected_hours_kms_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
