# Generated by Django 3.2.7 on 2021-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0036_auto_20211003_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='selected_hours_kms_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
