# Generated by Django 3.2.7 on 2021-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0037_auto_20211003_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='kms',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hours_kms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
