# Generated by Django 3.2.7 on 2021-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0039_auto_20211004_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='kms',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hours_kms_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
