# Generated by Django 3.2.7 on 2021-10-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0041_auto_20211014_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_location_start',
        ),
    ]
