# Generated by Django 3.2.7 on 2021-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0042_remove_reservation_date_location_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_location_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
