# Generated by Django 3.2.7 on 2021-10-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0043_reservation_date_location_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_location_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
