# Generated by Django 3.2.7 on 2021-10-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0047_alter_reservation_date_location_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
