# Generated by Django 2.2.24 on 2021-10-31 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_management', '0050_auto_20211031_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_location_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
