# Generated by Django 3.2.7 on 2021-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_price_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hoursDriving',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
