# Generated by Django 3.2.7 on 2021-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_price_category_hoursdriving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
