# Generated by Django 3.2.7 on 2021-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_price_category_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='car_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
