# Generated by Django 3.2.7 on 2021-09-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210926_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='kms',
        ),
    ]
