# Generated by Django 3.2.7 on 2021-09-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210926_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_category',
            name='kms',
        ),
    ]
