# Generated by Django 3.2.7 on 2021-09-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20210926_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illimited_kms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illimited_kms', models.CharField(blank=True, max_length=10, null=True)),
                ('price_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.price_category')),
            ],
        ),
    ]
