# Generated by Django 3.2.7 on 2021-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20210926_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_category',
            name='illimited_kms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
