# Generated by Django 3.2.7 on 2021-09-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_remove_price_category_illimited_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.CharField(blank=True, choices=[('4:00', '4:00'), ('6:00', '6:00'), ('12:00', '12:00')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, choices=[('150 kms', '150 kms'), ('200 kms', '200 kms'), ('illimited', 'illimited')], max_length=10, null=True),
        ),
    ]
