# Generated by Django 3.2.7 on 2021-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20210928_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_categories',
            field=models.ManyToManyField(blank=True, null=True, through='cars.Price', to='cars.Price_category'),
        ),
        migrations.AlterField(
            model_name='price',
            name='car_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.TimeField(blank=True, choices=[('4:00', '4:00'), ('6:00', '6:00'), ('12:00', '12:00')], null=True),
        ),
    ]
