# Generated by Django 3.2.7 on 2021-10-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_auto_20211004_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_categories',
            field=models.ManyToManyField(blank=True, through='cars.Price', to='cars.Price_category'),
        ),
    ]
