# Generated by Django 3.2.7 on 2021-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_auto_20211005_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.IntegerField(blank=True, choices=[(4, 4), (6, 6), (12, 12)], null=True),
        ),
    ]
