# Generated by Django 3.2.7 on 2021-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_alter_price_category_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='car_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='car_image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
