# Generated by Django 3.2.7 on 2021-10-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_auto_20211008_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_image',
            new_name='car_image1',
        ),
    ]
