# Generated by Django 3.2.7 on 2021-10-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_rename_car_image_car_car_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.IntegerField(blank=True, choices=[(4, 4), (6, 6), (12, 12), (24, 24), ('Week-end', 'Week-end'), ('Semaine', 'Semaine')], null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, choices=[(150, 150), (200, 200), (350, 350), (500, 500), (900, 900), ('illimited', 'illimited')], max_length=10, null=True),
        ),
    ]
