# Generated by Django 3.2.7 on 2021-10-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_auto_20211010_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_category',
            name='kms_illimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.CharField(blank=True, choices=[(4, 4), (6, 6), (12, 12), (24, 24), (72, 72)], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, choices=[(150, 150), (200, 200), (350, 350), (500, 500), (900, 900)], max_length=10, null=True),
        ),
    ]
