# Generated by Django 3.2.7 on 2021-10-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_auto_20211010_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_category',
            name='kms_illimited',
        ),
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('Week-end', 'Week-end')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, choices=[('150', '150'), ('200', '200'), ('350', '350'), ('500', '500'), ('900', '900'), ('illimited', 'illimited')], max_length=10, null=True),
        ),
    ]
