# Generated by Django 3.2.7 on 2021-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0034_auto_20211010_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.CharField(blank=True, choices=[('4h', '4h'), ('6h', '6'), ('12h', '12h'), ('24h', '24h'), ('Week-end', 'Week-end')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='price_category',
            name='kms',
            field=models.CharField(blank=True, choices=[('150 kms', '150 kms'), ('200 kms', '200 kms'), ('350 kms', '350 kms'), ('500 kms', '500 kms'), ('900 kms', '900 kms'), ('illimited', 'illimited')], max_length=10, null=True),
        ),
    ]
