# Generated by Django 3.2.7 on 2021-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_auto_20211010_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_category',
            name='hours',
            field=models.CharField(blank=True, choices=[('4h', '4h'), ('6h', '6h'), ('12h', '12h'), ('24h', '24h'), ('Week-end', 'Week-end')], max_length=20, null=True),
        ),
    ]
