# Generated by Django 3.2.7 on 2021-10-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_alter_price_category_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='summary',
        ),
    ]
