# Generated by Django 4.0.1 on 2022-01-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0041_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Titre',
        ),
    ]
