# Generated by Django 4.0.1 on 2022-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0047_remove_article_texte_alter_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
