# Generated by Django 4.0.1 on 2022-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0050_alter_article_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
