# Generated by Django 4.0.1 on 2022-01-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0053_alter_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Texte',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
