# Generated by Django 4.0.1 on 2022-01-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0059_alter_article_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Texte',
            field=models.TextField(null=True),
        ),
    ]
