# Generated by Django 4.0.1 on 2022-01-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0062_alter_article_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Texte',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Titre',
        ),
    ]
