# Generated by Django 4.0.1 on 2022-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0066_article_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Texte',
            field=models.TextField(null=True),
        ),
    ]
